spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gachi
    username: haza_user
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # update, validate, create-drop 등 필요에 맞게
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true  # 개발 단계에서만
